services:
  - type: worker
    name: bc-truck-works-bot
    runtime: node
    region: ohio
    rootDir: bot
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_CLIENT_ID
        value: "1556044045195935775"
      - key: DISCORD_GUILD_ID
        value: "1546265801500266611"
      - key: TRUCKWORKS_WEBSITE_URL
        value: "https://truck-works.vercel.app"
